use_frameworks!

platform :ios, '8.0'

target 'YTKJsBridge_Example' do
  pod 'YTKJsBridge', :path => '../'
end

target 'YTKJsBridge_Tests' do
    inherit! :search_paths
    pod 'YTKJsBridge', :path => '../'
end
